In [2]:
import numpy as np


In [3]:
list_ = ['1', '2' , '3', '4' , '5']


In [4]:
array_list = np.array(object = list_)

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
Ans- Yes,there is difference in the data type of variables list_ and array_list.


In [7]:
'''Code for question1'''  #for array_list
array_list.dtype        #dtype function tell the data type of array


dtype('<U1')

In [8]:
'''Code for question1''' #for list_

type(list_[0])

str

In [10]:
'''Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.'''
#Ans-

'''Code for printing the type of each data of List_'''
for i in range(len(list_)):
    print(type(list_[i]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [23]:
'''Code for printing the type of each data of array_list'''
length=np.size(array_list)   #size function is usded to get the length of array
for i in range(length):
    print(array_list[i].dtype)

<U1
<U1
<U1
<U1
<U1


Q3. Considering the following changes in the variable, array_list:
    
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [25]:
array_list = np.array(object = list_, dtype = int)

In [28]:
array_list

array([1, 2, 3, 4, 5])

In [ ]:
'''Ans Question(3)'''
Yes,the data type are changed in the array_list and data type of the list_ will not be changed


In [29]:
'''Code for Question(3) to check whether data type are changed or not for list_'''
for i in range(len(list_)):
    print(type(list_[i]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [30]:
'''Code for Question(3) to check whether data type are changed or not for array_list'''
length=np.size(array_list)
for i in range(length):
    print(array_list[i].dtype)

int64
int64
int64
int64
int64


In [31]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size


In [33]:
'''Code for Question(4) '''   
#(i).shape
np.shape(num_array)     #

(2, 3)

In [34]:
'''Code for Question(4)'''
#(ii) size
np.size(num_array)


6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [35]:
'''code for Question(4) for creating numpy array of 3*3'''
np.zeros((3,3))   #This function create zero matrix and (3,3) is passed as order of matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [36]:
'''Ans for Question(6)'''
np.eye(5)  #this function is used to create identity matrix  and 5 has been passed as order of matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])